export const IPC = {
  workspaceLoad: 'workspace:load',
  workspaceSave: 'workspace:save',
  ptyCreate: 'pty:create',
  ptyInput: 'pty:input',
  ptyResize: 'pty:resize',
  ptyKill: 'pty:kill',
  ptyData: 'pty:data',
  ptyExit: 'pty:exit',
  dialogPickDirectory: 'dialog:pickDirectory',
  shellOpenPath: 'shell:openPath',
  ptyProc: 'pty:proc',
  dialogPickFile: 'dialog:pickFile',
  reviewSuggestSpec: 'review:suggestSpec',
  reviewResolveDir: 'review:resolveDir',
  reviewResolveTranscript: 'review:resolveTranscript',
  fsRead: 'fs:read',
  fsWatch: 'fs:watch',
  fsUnwatch: 'fs:unwatch',
  fsChanged: 'fs:changed',
  ptyBusy: 'pty:busy',
  agentCaptureSession: 'agent:captureSession'
} as const
